### ISSUE TITLE
No more pr to be accepted

### ISSUE THREAD

**Issue by abhishekprasad2384** [flyingsonu122/links-list#21]
Hii there first of all sorry for all the interested candidate who wants to contribute in this repo , Since as we all know many repo has been already excluded from hacktoberfest because of many acceptance of pr . That's why to save our already contributed member we should stop accepting any more pr in order to protect our community.

**Comment by flyingsonu122** [comment]
@abhishekprasad2384 
this project is not for increasing your PR count, it is for listing  profiles of developer around the world.
